# Generated by Django 2.1 on 2018-08-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'base_manager_name': 'data', 'default_manager_name': 'data', 'get_latest_by': 'created', 'ordering': ['-created'], 'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='location_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='class_name',
            field=models.CharField(default='', max_length=150, verbose_name='Schule / Klasse'),
        ),
    ]
