# Generated by Django 2.1 on 2018-08-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0002_auto_20180831_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='places',
            field=models.IntegerField(default=0, verbose_name='Anzahl Plätze'),
        ),
    ]
