# Generated by Django 2.1 on 2018-08-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0004_auto_20180831_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
