# Generated by Django 2.1 on 2018-09-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0005_auto_20180831_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'base_manager_name': 'data', 'default_manager_name': 'data', 'get_latest_by': 'created', 'ordering': ['-start'], 'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'base_manager_name': 'data', 'default_manager_name': 'data', 'get_latest_by': 'created', 'ordering': ['-paid', 'created'], 'verbose_name': 'Anfrage', 'verbose_name_plural': 'Anfragen'},
        ),
        migrations.AddField(
            model_name='event',
            name='for_schools',
            field=models.BooleanField(default=True, verbose_name='Für (Vor-)Schulkinder'),
        ),
    ]
