# Generated by Django 2.1 on 2018-09-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0007_auto_20180905_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='places',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='adults',
            field=models.IntegerField(default=0, verbose_name='Anzahl Erwachsene'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='kids',
            field=models.IntegerField(default=0, verbose_name='Anzahl Kinder'),
        ),
    ]
